### ISSUE TITLE
Transfer pymsmt to amber-md

### ISSUE THREAD

**Issue by swails** [Amber-MD/pymsmt#3]
Hi Pengfei,

I just made you an "owner" of the Amber-MD organization.  I was hoping to be able to convince you to transfer the pymsmt repository over to the Amber-MD organization (you will still have control over merging pull requests and stuff like that), but I think it would be nice if we started migrating Amber components over to that umbrella.

What do you think?

**Comment by pengfeili1** [comment]
Hi Jason,

Thanks for your help. I will be out of town this weekend. I will begin to deal with this issue next week.

All the best,
Pengfei

**Comment by hainm** [comment]
@pengfeili1 I just transfer `pytraj` to `amber-md` smoothly (just from the link I sent you in email).

**Comment by pengfeili1** [comment]
Hi Hai, I just transferred pymsmt to Amber-MD as well.
