### ISSUE TITLE
travis test

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pymsmt#4]
hi,

you can add travis for building and testing pymsmt too.

check parmed/.travis.yml and pytraj/.travis.yml and cpptraj/.travis.yml for details.

http://docs.travis-ci.com/user/languages/python/

**Comment by pengfeili1** [comment]
Hi Hai, does travis needs the program as standalone version? My code could not run without AmberTools15.

**Comment by hainm** [comment]
Uhm. So it is not possible. Cpptraj, pytraj and parmed have their own build
and tests. What part of AT you need? Sander?

Hai

On Saturday, August 8, 2015, pengfeili1 <notifications@github.com> wrote:

> Hi Hai, does travis needs the program as standalone version? My code could
> not run without AmberTools15.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Amber-MD/pymsmt/issues/4#issuecomment-129042903>.
>


-- 
Hai Nguyen

**Comment by pengfeili1** [comment]
I need the force field parameter files and also a periodic table dictionary in ParmEd. I am not sure whether I can copy these files or code into pymsmt directory or subdirectories directly. How do you think?

**Comment by hainm** [comment]
@pengfeili1 you can treat `travis` as your personal computer. You can git clone parmed to travis, install parmed and use it. Make sure to change 'chemistry` to `parmed`. Just read .travis file in `pytraj` and `parmed` repos to see the detail.

Per FF file, you can look at https://github.com/choderalab/ambermini here. Or you can make a copy to your folder.

**Comment by hainm** [comment]
https://github.com/Amber-MD/pytraj/blob/master/devtools/travis-ci/setup_env.sh

**Comment by pengfeili1** [comment]
Thanks Hai. I made a standalone version of pymsmt. The installation is fine on Travis CI website, but the package could not be import after installation. Can you help check what is wrong based on the last log in https://travis-ci.org/Amber-MD/pymsmt ? Thanks!

**Comment by hainm** [comment]
Hi

Have you exported pythonpath to where you install yet?

Hai

**Comment by hainm** [comment]
And I recommend to use minaconda to install python, numpy, ... We should avoid using 'sudo'

Check parmed about this and google why. :d

Hai
